Added a test against memory.
By default, the script will use one processor to recompile everything,
which is the safest way to compile (i.e. you are much less likely to run
out of memory).

We expect each process to use around 4Gb of memory, so we compute the
maximum number of processors as:

  processors = free-memory / 4

and compare that with the number you specified with --processors=...
and if you used a larger number, we warning you about compiling with that
many processors. (i.e. you're likely to blow your memory away and swap
like crazy and it won't be any faster than using a single processor all
the way).

So if you have 16 processors, we expect you to have at least 64Gb of free
memory (so probably 128Gb total since some is used by the system and other
tasks).

diff --git a/bin/build-snap b/bin/build-snap
--- a/bin/build-snap
+++ b/bin/build-snap
@@ -131,6 +131,40 @@ do
 	esac
 done
 
+if test ${PROCESSORS} -le 0
+then
+	echo "error: the number of processors must be a positive number."
+	exit 1
+fi
+
+# Verify memory levels
+FREE_MEM=`grep MemFree: /proc/meminfo | awk '{ print int($2 / 1048576) }'`
+REQUIRED_MEM=`expr ${PROCESSORS} \* 40`
+if test ${FREE_MEM} -lt ${REQUIRED_MEM}
+then
+	echo "warning: you are low on memory..."
+	if test ${PROCESSORS} -eq 1
+	then
+		echo "warning: since you requested a single processor, you probably don't have much chose at the moment."
+	else
+		MAX_PROCESSORS=`expr ${FREE_MEM} / 40`
+		if test ${MAX_PROCESSORS} -le 0
+		then
+			echo "warning: we suggest you try to compile with a single processor"
+		else
+			echo "warning: we suggest you try compiling with only ${MAX_PROCESSORS} processors"
+		fi
+	fi
+	echo -n "warning: do you want to continue with ${PROCESSORS} processors? (y/[N]) "
+	read ANSWER
+	if test "${ANSWER}" != "y" -a "${ANSWER}" != "Y"
+	then
+		echo "error: build process aborted."
+		exit 1
+	fi
+fi
+
+
 echo "info: Use ${PROCESSORS} processors to compile Snap! C++"
 
 if test -n "$DEBUILD_EMAIL"
