SNAP-406: actually added an if around the snapcreatetables to avoid errors in our postinst scripts.

diff --git a/snapwebsites/snapbackend/debian/snapbackend.postinst b/snapwebsites/snapbackend/debian/snapbackend.postinst
--- a/snapwebsites/snapbackend/debian/snapbackend.postinst
+++ b/snapwebsites/snapbackend/debian/snapbackend.postinst
@@ -9,7 +9,10 @@ if [ "$1" = "configure" ]
 then
     # Make sure that the core table exists
     #
-    snapcreatetables
+    if ! snapcreatetables
+    then
+        echo "notice: snapcreatetables failed."
+    fi
 
     for pkg in snapbackend snapsendmail snapimages snappagelist
     do
diff --git a/snapwebsites/snapserver-core-plugins/debian/snapserver-core-plugins.postinst b/snapwebsites/snapserver-core-plugins/debian/snapserver-core-plugins.postinst
--- a/snapwebsites/snapserver-core-plugins/debian/snapserver-core-plugins.postinst
+++ b/snapwebsites/snapserver-core-plugins/debian/snapserver-core-plugins.postinst
@@ -26,7 +26,10 @@ then
 
     # Make sure that the plugin tables exist
     #
-    snapcreatetables
+    if ! snapcreatetables
+    then
+        echo "notice: snapcreatetables failed."
+    fi
 
     # if snapinit is already running, we need to give it a kick
     #
diff --git a/snapwebsites/snapserver/debian/snapserver.postinst b/snapwebsites/snapserver/debian/snapserver.postinst
--- a/snapwebsites/snapserver/debian/snapserver.postinst
+++ b/snapwebsites/snapserver/debian/snapserver.postinst
@@ -11,7 +11,10 @@ then
 
     # Make sure that the core table exists
     #
-    snapcreatetables
+    if ! snapcreatetables
+    then
+        echo "notice: snapcreatetables failed."
+    fi
 
     if systemctl is-enabled ${PKGNAME} 2> /dev/null
     then
diff --git a/snapwebsites/snapwatchdog/debian/snapwatchdog.postinst b/snapwebsites/snapwatchdog/debian/snapwatchdog.postinst
--- a/snapwebsites/snapwatchdog/debian/snapwatchdog.postinst
+++ b/snapwebsites/snapwatchdog/debian/snapwatchdog.postinst
@@ -31,7 +31,10 @@ then
 
     # Make sure that the snapwatchdog table exists
     #
-    snapcreatetables
+    if ! snapcreatetables
+    then
+        echo "notice: snapcreatetables failed."
+    fi
 
     if systemctl is-enabled ${PKGNAME} 2> /dev/null
     then
