SNAP-3: Create a proper source package when building libtld with dev/build (i.e. added a cmake directory) Added test to verify version of the validate_tld tool. Added a funtion to quote the different email parts. Updated the tests that now would fail since the quotation is correct!

diff --git a/libtld/dev/coverage b/libtld/dev/coverage
--- a/libtld/dev/coverage
+++ b/libtld/dev/coverage
@@ -65,6 +65,11 @@ then
     echo "validate_tld --list did not exit with an error";
     exit 1;
 fi
+if BUILD/src/validate_tld -v --version
+then
+    echo "validate_tld --list did not exit with an error";
+    exit 1;
+fi
 if ! BUILD/src/validate_tld http://www.m2osw.com/validate/tld?perfect=work
 then
     echo "validate_tld <valid URI> did exit with an error";
