SNAP-465: Fixed the test to block proxy attempts received by snap.cgi.
Changed the block to 1 year on a proxy attempt.
Added a test, if snap.cgi receives /xmlrpc.php, we block that IP immediately.
Clearly marked that block_ip()'s default period is "day".
Added '\d+' to the failregex of the badrequest.
Added a new 'unwanted' apache jail for valid requests we do not want.
Actually install the new count-unwanted script.
Removed the 'sudo' from the count-unwanted and check that we are root.
Made 'bc' a dependency of snapfirewall since we use it in a script.
Changed the BLOCK behavior, accept an undefined period as "day".

diff --git a/snapwebsites/snapfirewall/src/count-unwanted b/snapwebsites/snapfirewall/src/count-unwanted
--- a/snapwebsites/snapfirewall/src/count-unwanted
+++ b/snapwebsites/snapfirewall/src/count-unwanted
@@ -2,6 +2,12 @@
 #
 # This script counts the number of entries in the unwanted chain of iptables
 
+if test "`whoami`" != "root"
+then
+        echo "error: root access is required, trie 'sudo $0' instead"
+        exit 1
+fi
+
 CHAIN=unwanted
 
 if test -n "$1"
@@ -18,12 +24,12 @@ COUNT=`iptables -nvx -L "$CHAIN" | sed -e '1,2 d' | wc -l`
 # Then we sum column 1, which represents the total number of hits since the
 # block of those IPs occurred
 #
-HITS=`sudo iptables -nvx -L "$CHAIN" | sed -e '1,2 d' -e 's/^\s*\([0-9]\+\)\s.*$/\1/' | awk '{s+=$1} END {print s}'`
+HITS=`iptables -nvx -L "$CHAIN" | sed -e '1,2 d' -e 's/^\s*\([0-9]\+\)\s.*$/\1/' | awk '{s+=$1} END {print s}'`
 
 # Then we sum column 2, which represents the total number of bytes received
 # since the block of those IPs occurred
 #
-BYTES=`sudo iptables -nvx -L "$CHAIN" | sed -e '1,2 d' -e 's/^\s*[0-9]\+\s*\([0-9]\+\)\s.*$/\1/' | awk '{s+=$1} END {print s}'`
+BYTES=`iptables -nvx -L "$CHAIN" | sed -e '1,2 d' -e 's/^\s*[0-9]\+\s*\([0-9]\+\)\s.*$/\1/' | awk '{s+=$1} END {print s}'`
 
 # Compute the average number of bytes per hit
 #
